### ISSUE TITLE
Trouble for "wheels for collected packages: cosmosis-standalone, pyccl, firecrown"

### ISSUE THREAD

**Issue by jecampagne** [LSSTDESC/tomo_challenge#14]
Hi Folks
I was aiming to install this promising challenge and jump to my Mac BP on a fresh Catalina install.  So following the Install guide

`pip install -r requirements.txt`

Here is the full crash log, I'm using Python 3.7 and pip 20.0.2 from Anaconda  4.8.3

An idea?
Sincerelly
Jean-Eric

```
Building wheels for collected packages: cosmosis-standalone, pyccl, firecrown
  Building wheel for cosmosis-standalone (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/campagne/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py'"'"'; __file__='"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-wheel-fixhzmin
       cwd: /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/
  Complete output (104 lines):
  running bdist_wheel
  running build
  /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis
  make: Entering directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis'
  make[1]: Entering directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis/datablock'
  c++ -O3 -g -fPIC -I/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis/.. -Wall -Wextra -pedantic -std=c++14   -c -o datablock.o datablock.cc
  In file included from datablock.cc:1:
  In file included from ./datablock.hh:45:
  In file included from ./section.hh:9:
  In file included from ./entry.hh:5:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
  using ::signbit;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
  using ::fpclassify;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
  using ::isfinite;
        ~~^
  /usr/local/include/math.h:749:12: note: 'finite' declared here
  extern int finite(double)
             ^
  In file included from datablock.cc:1:
  In file included from ./datablock.hh:45:
  In file included from ./section.hh:9:
  In file included from ./entry.hh:5:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
  using ::isinf;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
  using ::isnan;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
  using ::isnormal;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
  using ::isgreater;
        ^~
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:731:29: note: '::std::greater' declared here
  struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                              ^
  In file included from datablock.cc:1:
  In file included from ./datablock.hh:45:
  In file included from ./section.hh:9:
  In file included from ./entry.hh:5:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
  using ::isgreaterequal;
        ^~
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:760:29: note: '::std::greater_equal' declared here
  struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                              ^
  In file included from datablock.cc:1:
  In file included from ./datablock.hh:45:
  In file included from ./section.hh:9:
  In file included from ./entry.hh:5:
  In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
  using ::isless;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
  using ::islessequal;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
  using ::islessgreater;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  13 errors generated.
  make[1]: *** [datablock.o] Error 1
  make[1]: Leaving directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis/datablock'
  make: *** [all] Error 2
  make: Leaving directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 128, in <module>
      version=version,
    File "/Users/campagne/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/campagne/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 94, in run
      compile_library()
    File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 83, in compile_library
      subprocess.check_call(["make"], env=env, cwd="cosmosis")
    File "/Users/campagne/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for cosmosis-standalone
  Running setup.py clean for cosmosis-standalone
  Building wheel for pyccl (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/campagne/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/setup.py'"'"'; __file__='"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-wheel-ymm7bj25
       cwd: /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/
  Complete output (127 lines):
  running bdist_wheel
  running build
  running build_py
  -- No build type selected, default to Release
  -- CMAKE_BUILD_TYPE: Release
  -- The C compiler identification is AppleClang 11.0.3.11030032
  -- The CXX compiler identification is AppleClang 11.0.3.11030032
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Warning (dev) at /opt/local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
    The package name passed to `find_package_handle_standard_args` (PkgConfig)
    does not match the name of the calling package (FFTW).  This can lead to
    problems in calling code that expects `find_package` result variables
    (e.g., `_FOUND`) to follow a certain pattern.
  Call Stack (most recent call first):
    /opt/local/share/cmake-3.17/Modules/FindPkgConfig.cmake:45 (find_package_handle_standard_args)
    cmake/Modules/FindFFTW.cmake:18 (include)
    cmake/Modules/BuildFFTW.cmake:6 (find_package)
    CMakeLists.txt:47 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.2")
  -- Found FFTW: /opt/local/include
  -- Found GSL: /opt/local/include (found suitable version "2.6", minimum required is "2.1")
  -- Found SWIG: /opt/local/bin/swig (found version "4.0.2")
  -- Found PythonInterp: /Users/campagne/anaconda3/bin/python3.7 (found suitable version "3.7.1", minimum required is "3.7.1")
  -- Found PythonLibs: /Users/campagne/anaconda3/lib/libpython3.7m.dylib
  -- Found PythonInterp: /Users/campagne/anaconda3/bin/python3.7 (found version "3.7.1")
  -- Found NumPy: version "1.18.5" /Users/campagne/anaconda3/lib/python3.7/site-packages/numpy/core/include
  CMake Warning (dev) at /opt/local/share/cmake-3.17/Modules/UseSWIG.cmake:607 (message):
    Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
    "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
    command to set the policy and suppress this warning.
  
  Call Stack (most recent call first):
    pyccl/CMakeLists.txt:28 (swig_add_library)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  CMake Warning (dev) at /opt/local/share/cmake-3.17/Modules/UseSWIG.cmake:460 (message):
    Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
    flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.
  
  Call Stack (most recent call first):
    /opt/local/share/cmake-3.17/Modules/UseSWIG.cmake:702 (SWIG_ADD_SOURCE_TO_MODULE)
    pyccl/CMakeLists.txt:28 (swig_add_library)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/build
  Scanning dependencies of target objlib
  [  3%] Building C object CMakeFiles/objlib.dir/src/ccl_background.c.o
  [  7%] Building C object CMakeFiles/objlib.dir/src/ccl_core.c.o
  [ 11%] Building C object CMakeFiles/objlib.dir/src/ccl_error.c.o
  [ 15%] Building C object CMakeFiles/objlib.dir/src/ccl_bbks.c.o
  [ 19%] Building C object CMakeFiles/objlib.dir/src/ccl_f1d.c.o
  [ 23%] Building C object CMakeFiles/objlib.dir/src/ccl_f2d.c.o
  [ 26%] Building C object CMakeFiles/objlib.dir/src/ccl_power.c.o
  [ 30%] Building C object CMakeFiles/objlib.dir/src/ccl_bcm.c.o
  [ 34%] Building C object CMakeFiles/objlib.dir/src/ccl_eh.c.o
  [ 38%] Building C object CMakeFiles/objlib.dir/src/ccl_musigma.c.o
  [ 42%] Building C object CMakeFiles/objlib.dir/src/ccl_utils.c.o
  [ 46%] Building C object CMakeFiles/objlib.dir/src/ccl_cls.c.o
  [ 50%] Building C object CMakeFiles/objlib.dir/src/ccl_massfunc.c.o
  [ 53%] Building C object CMakeFiles/objlib.dir/src/ccl_neutrinos.c.o
  [ 57%] Building C object CMakeFiles/objlib.dir/src/ccl_emu17.c.o
  [ 61%] Building C object CMakeFiles/objlib.dir/src/ccl_correlation.c.o
  [ 65%] Building C object CMakeFiles/objlib.dir/src/ccl_halofit.c.o
  [ 69%] Building C object CMakeFiles/objlib.dir/src/ccl_haloprofile.c.o
  [ 73%] Building C object CMakeFiles/objlib.dir/src/ccl_tracers.c.o
  [ 76%] Building C object CMakeFiles/objlib.dir/src/ccl_mass_conversion.c.o
  [ 80%] Building C object CMakeFiles/objlib.dir/src/ccl_fftlog.c.o
  [ 80%] Built target objlib
  Scanning dependencies of target ccl
  [ 84%] Linking C shared library libccl.dylib
  [ 84%] Built target ccl
  Scanning dependencies of target ccl_static
  [ 88%] Linking C static library libccl_static.a
  [ 88%] Built target ccl_static
  Scanning dependencies of target ccllib_swig_compilation
  [ 92%] Swig compile ccl.i for python
  :3: Error: Unable to find 'python.swg'
  make[3]: *** [pyccl/CMakeFiles/_ccllib.dir/cclPYTHON.stamp] Error 1
  make[3]: *** Deleting file `pyccl/CMakeFiles/_ccllib.dir/cclPYTHON.stamp'
  make[2]: *** [pyccl/CMakeFiles/ccllib_swig_compilation.dir/all] Error 2
  make[1]: *** [pyccl/CMakeFiles/_ccllib.dir/rule] Error 2
  make: *** [_ccllib] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/setup.py", line 78, in <module>
      'Topic :: Scientific/Engineering :: Physics'
    File "/Users/campagne/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/campagne/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/setup.py", line 38, in run
      _compile_ccl()
    File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/pyccl/setup.py", line 22, in _compile_ccl
      raise Exception("Could not build CCL")
  Exception: Could not build CCL
  ----------------------------------------
  ERROR: Failed building wheel for pyccl
  Running setup.py clean for pyccl
  Building wheel for firecrown (setup.py) ... done
  Created wheel for firecrown: filename=firecrown-0.3.0-py3-none-any.whl size=49957 sha256=eb4c32204f7cef1d974545b386991286f333de54c9a9d1c3b8a3a1e7e17d4e3f
  Stored in directory: /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-ephem-wheel-cache-zp34rpdn/wheels/a0/9b/7f/0e69d1a04a2162acb5f5af82982f96543dc870cd0aeb70a4b3
Successfully built firecrown
Failed to build cosmosis-standalone pyccl
Installing collected packages: cosmosis-standalone, pyccl, mpmath, sympy, camb, progressbar, firecrown
    Running setup.py install for cosmosis-standalone ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/campagne/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py'"'"'; __file__='"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-record-gfcrbhl8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/campagne/anaconda3/include/python3.7m/cosmosis-standalone
         cwd: /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/
    Complete output (108 lines):
    running install
    running build
    /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis
    make: Entering directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis'
    make[1]: Entering directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis/datablock'
    c++ -O3 -g -fPIC -I/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis/.. -Wall -Wextra -pedantic -std=c++14   -c -o datablock.o datablock.cc
    In file included from datablock.cc:1:
    In file included from ./datablock.hh:45:
    In file included from ./section.hh:9:
    In file included from ./entry.hh:5:
    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
    using ::signbit;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
    using ::fpclassify;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
    using ::isfinite;
          ~~^
    /usr/local/include/math.h:749:12: note: 'finite' declared here
    extern int finite(double)
               ^
    In file included from datablock.cc:1:
    In file included from ./datablock.hh:45:
    In file included from ./section.hh:9:
    In file included from ./entry.hh:5:
    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
    using ::isinf;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
    using ::isnan;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
    using ::isnormal;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
    using ::isgreater;
          ^~
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:731:29: note: '::std::greater' declared here
    struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                                ^
    In file included from datablock.cc:1:
    In file included from ./datablock.hh:45:
    In file included from ./section.hh:9:
    In file included from ./entry.hh:5:
    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
    using ::isgreaterequal;
          ^~
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:760:29: note: '::std::greater_equal' declared here
    struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                                ^
    In file included from datablock.cc:1:
    In file included from ./datablock.hh:45:
    In file included from ./section.hh:9:
    In file included from ./entry.hh:5:
    In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/complex:245:
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
    using ::isless;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
    using ::islessequal;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
    using ::islessgreater;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
    using ::isunordered;
          ~~^
    13 errors generated.
    make[1]: *** [datablock.o] Error 1
    make[1]: Leaving directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis/datablock'
    make: *** [all] Error 2
    make: Leaving directory `/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/cosmosis'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 128, in <module>
        version=version,
      File "/Users/campagne/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "/Users/campagne/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 106, in run
        super().run()
      File "/Users/campagne/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/campagne/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/campagne/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/campagne/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 94, in run
        compile_library()
      File "/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py", line 83, in compile_library
        subprocess.check_call(["make"], env=env, cwd="cosmosis")
      File "/Users/campagne/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/campagne/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py'"'"'; __file__='"'"'/private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-install-9yib806q/cosmosis-standalone/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/mq/xz6p51gj4jz5d_t5yxvx2hsr0000gp/T/pip-record-gfcrbhl8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/campagne/anaconda3/include/python3.7m/cosmosis-standalone Check the logs for full command output.
```

**Comment by joezuntz** [comment]
Hi @jecampagne ,

The easiest solution will be to install the conda versions of the packages:
```
conda install cosmosis pyccl cosmosis-standalone --channel conda-forge 
```

In case this bug hits you later in other contexts, I found this referring to the CosmoSIS issue:
https://stackoverflow.com/questions/58628377/catalina-c-using-cmath-headers-yield-error-no-member-named-signbit-in-th

**Comment by jecampagne** [comment]
Hi Joe,
I have been in touch with @EiffL and 
1) I exactly install pyccl, firecrown, cosmosis-standalone with conda
2) I have commented the corresponding lines in the requirements.txt file
3) I have then proceed to the pip install
=> seems ok, but is there a "test-your-install" procedure?

**Comment by joezuntz** [comment]
Great - for a quick test you can run the same thing the continuous integration runs:

```
mkdir data
curl -o data/mini_training.hdf5 https://portal.nersc.gov/project/lsst/txpipe/tomo_challenge_data/ugrizy/mini_training.hdf5
curl -o data/mini_validation.hdf5 https://portal.nersc.gov/project/lsst/txpipe/tomo_challenge_data/ugrizy/mini_validation.hdf5
export PYTHONPATH=$PYTHONPATH:$PWD
python bin/challenge.py example/ci.yml
```

**Comment by jecampagne** [comment]
Ha! ok, I have jumped to the 
`python -m tomo_challenge.data` which went smoothly and then
`python bin/challenge.py example/example.yaml` which is currently in 'Applying...' phase 
I will let you know asap

**Comment by joezuntz** [comment]
That’s great - thanks for getting involved! Please do reopen this or another issue if you have any more questions or problems.
