### ISSUE TITLE
NameError in jax_metrics.py

### ISSUE THREAD

**Issue by dylanagreen** [LSSTDESC/tomo_challenge#26]
When trying to measure the metrics of any classifier with the jax-cosmo implementation, the program throws an exception:
```
Traceback (most recent call last):
  File "bin/challenge.py", line 111, in <module>
    main()
  File "/Users/dylan/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dylan/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dylan/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dylan/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "bin/challenge.py", line 67, in main
    config['metrics'], metrics_fn)
  File "bin/challenge.py", line 101, in run_one
    scores = metrics_fn(results, valid_z, metrics=metrics)
  File "bin/../tomo_challenge/jax_metrics.py", line 227, in compute_scores
    scores['SNR_'+what] = float(compute_snr_score(tomo_bin, z, what=what, binned_nz=True))
  File "bin/../tomo_challenge/jax_metrics.py", line 98, in compute_snr_score
    probes = get_probes(weights, labels, what=what, binned_nz=binned_nz)
  File "bin/../tomo_challenge/jax_metrics.py", line 52, in get_probes
    fractions = np.array([c / len(labels) for c in counts])
NameError: name 'np' is not defined
```
This error can be reproduced by running `python bin/challenge.py example/example_jax.yaml` or by calling `tc.jc_compute_scores(tomo_bin, z)` on any valid binning.

**Comment by EiffL** [comment]
Hi @dylanagreen , thanks for this bug report! I see the problem, will be fixed shortly, sorry for the trouble.

**Comment by EiffL** [comment]
There, it should work now if you pull from the main branch :-) Let me know if it still gives you problems
